# docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: guss_db
      POSTGRES_USER: guss_user
      POSTGRES_PASSWORD: guss_pass
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
